import Foundation
import os.log

private let logger = Logger(subsystem: "com.rockpile.app", category: "HookInstaller")

/// Installs bash hooks into ~/.claude/hooks/ for Claude Code integration.
///
/// Unlike the legacy PluginInstaller (JS plugin → ~/.rockpile/plugins/),
/// this writes a bash script that pipes Claude Code events to /tmp/rockpile.sock.
/// Claude Code discovers hooks via ~/.claude/settings.json → hooks section.
enum HookInstaller {
    private static let hookFileName = "rockpile-hook.sh"
    private static let socketPath = "/tmp/rockpile.sock"

    private static var hooksDir: URL {
        FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".claude/hooks")
    }

    private static var hookFilePath: URL {
        hooksDir.appendingPathComponent(hookFileName)
    }

    private static var settingsPath: URL {
        FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".claude/settings.json")
    }

    // MARK: - Public API

    /// Install hook if ~/.claude/ exists and hook isn't already installed.
    static func installIfNeeded() {
        let claudeDir = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".claude")
        guard FileManager.default.fileExists(atPath: claudeDir.path) else {
            logger.info("~/.claude not found, skipping hook install")
            return
        }

        // Check if hook script already exists and is up-to-date
        if let existing = try? String(contentsOf: hookFilePath, encoding: .utf8),
           existing.contains(socketPath) {
            logger.info("Hook already installed and up-to-date")
            registerInSettings()
            return
        }

        install()
    }

    /// Force install (or reinstall) the hook.
    static func install() {
        let fm = FileManager.default

        // Create hooks directory
        do {
            try fm.createDirectory(at: hooksDir, withIntermediateDirectories: true)
        } catch {
            logger.error("Failed to create hooks dir: \(error.localizedDescription)")
            return
        }

        // Write hook script
        let script = generateHookScript()
        do {
            try script.write(to: hookFilePath, atomically: true, encoding: .utf8)
            // Make executable
            try fm.setAttributes([.posixPermissions: 0o755], ofItemAtPath: hookFilePath.path)
            logger.info("Hook script installed to \(hookFilePath.path, privacy: .public)")
        } catch {
            logger.error("Failed to write hook script: \(error.localizedDescription)")
            return
        }

        registerInSettings()
    }

    /// Remove hook script and unregister from settings.json.
    static func uninstall() {
        try? FileManager.default.removeItem(at: hookFilePath)
        unregisterFromSettings()
        logger.info("Hook uninstalled")
    }

    // MARK: - Hook Script Generation

    private static func generateHookScript() -> String {
        // swiftlint:disable line_length
        """
        #!/bin/bash
        # Rockpile Hook — forwards Claude Code events to Rockpile app via Unix socket
        # Auto-generated by Rockpile. Do not edit manually.

        SOCKET_PATH="\(socketPath)"

        # Exit silently if socket doesn't exist (app not running)
        [ -S "$SOCKET_PATH" ] || exit 0

        /usr/bin/python3 -c "
        import json, socket, sys, time, os

        try:
            input_data = json.load(sys.stdin)
        except:
            sys.exit(0)

        hook_event = input_data.get('hook_event_name', '')

        event_map = {
            'UserPromptSubmit': ('MessageReceived', 'working'),
            'PreCompact': ('Compaction', 'compacting'),
            'SessionStart': ('SessionStart', 'idle'),
            'SessionEnd': ('SessionEnd', 'ended'),
            'PreToolUse': ('ToolCall', 'working'),
            'PostToolUse': ('ToolResult', 'working'),
            'PermissionRequest': ('PermissionRequest', 'waiting'),
            'Stop': ('AgentEnd', 'idle'),
            'SubagentStop': ('SubagentEnded', 'idle'),
        }

        mapped = event_map.get(hook_event)
        if not mapped:
            sys.exit(0)

        event_name, default_status = mapped
        has_error = hook_event == 'PostToolUse' and input_data.get('error')
        status = 'error' if has_error else default_status

        output = {
            'session_id': input_data.get('session_id', ''),
            'event': event_name,
            'status': status,
            'cwd': input_data.get('cwd', ''),
            'ts': int(time.time() * 1000),
        }

        if hook_event == 'UserPromptSubmit':
            prompt = input_data.get('prompt', '')
            if prompt:
                output['user_prompt'] = prompt[:500]

        tool = input_data.get('tool_name', '')
        if tool:
            output['tool'] = tool
        if has_error:
            output['error'] = str(input_data.get('error', ''))[:200]

        tool_id = input_data.get('tool_use_id', '')
        if tool_id:
            output['tool_use_id'] = tool_id

        tool_input = input_data.get('tool_input', {})
        if tool_input and isinstance(tool_input, dict):
            truncated = {}
            for k, v in list(tool_input.items())[:5]:
                sv = str(v)
                truncated[k] = sv[:200] if len(sv) > 200 else sv
            output['tool_input'] = truncated

        # Send to socket
        try:
            sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
            sock.settimeout(2)
            sock.connect('$SOCKET_PATH')
            sock.sendall(json.dumps(output).encode())
            sock.close()
        except:
            pass

        # PermissionRequest: poll for Rockpile's response file
        if hook_event == 'PermissionRequest' and tool_id:
            response_file = f'/tmp/rockpile-permission-{tool_id}.json'
            timeout = 300  # 5 minutes
            start = time.time()
            while time.time() - start < timeout:
                if os.path.exists(response_file):
                    try:
                        with open(response_file) as f:
                            resp = json.load(f)
                        os.unlink(response_file)
                        decision = resp.get('decision', 'deny')
                        result = {'decision': 'allow' if decision == 'allow' else 'deny'}
                        print(json.dumps(result))
                        sys.exit(0)
                    except:
                        pass
                time.sleep(0.5)
            # Timeout — deny
            print(json.dumps({'decision': 'deny'}))
        "
        """
        // swiftlint:enable line_length
    }

    // MARK: - Settings.json Registration

    /// Hook events that Rockpile listens to
    private static let hookEvents: [(event: String, matcher: String?)] = [
        ("UserPromptSubmit", nil),
        ("PreToolUse", "*"),
        ("PostToolUse", "*"),
        ("PermissionRequest", "*"),
        ("PreCompact", "auto"),
        ("PreCompact", "manual"),
        ("SessionStart", nil),
        ("SessionEnd", nil),
        ("Stop", nil),
        ("SubagentStop", nil),
    ]

    private static func registerInSettings() {
        let hookCommand = "~/.claude/hooks/\(hookFileName)"

        // Read existing settings (with backup if parse fails)
        var settings: [String: Any]
        if let data = try? Data(contentsOf: settingsPath) {
            if let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any] {
                settings = json
            } else {
                // Malformed JSON — backup before overwriting
                logger.warning("settings.json malformed, creating backup")
                let backup = settingsPath.deletingPathExtension().appendingPathExtension("backup.json")
                try? data.write(to: backup)
                settings = [:]
            }
        } else {
            settings = [:]
        }

        var hooks = settings["hooks"] as? [String: Any] ?? [:]

        for (event, matcher) in hookEvents {
            var eventEntries = hooks[event] as? [[String: Any]] ?? []

            // Check if our hook is already registered for this event+matcher
            let alreadyRegistered = eventEntries.contains { entry in
                guard let entryHooks = entry["hooks"] as? [[String: Any]] else { return false }
                let matcherMatch: Bool
                if let matcher = matcher {
                    matcherMatch = (entry["matcher"] as? String) == matcher
                } else {
                    matcherMatch = entry["matcher"] == nil
                }
                return matcherMatch && entryHooks.contains { ($0["command"] as? String) == hookCommand }
            }

            if !alreadyRegistered {
                var entry: [String: Any] = [
                    "hooks": [["command": hookCommand, "type": "command"]],
                ]
                if let matcher = matcher {
                    entry["matcher"] = matcher
                }
                eventEntries.append(entry)
                hooks[event] = eventEntries
            }
        }

        settings["hooks"] = hooks

        // Write back
        do {
            let data = try JSONSerialization.data(withJSONObject: settings, options: [.prettyPrinted, .sortedKeys])
            try data.write(to: settingsPath, options: .atomic)
            logger.info("Registered hooks in settings.json")
        } catch {
            logger.error("Failed to update settings.json: \(error.localizedDescription)")
        }
    }

    private static func unregisterFromSettings() {
        let hookCommand = "~/.claude/hooks/\(hookFileName)"

        guard let data = try? Data(contentsOf: settingsPath),
              var settings = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              var hooks = settings["hooks"] as? [String: Any] else { return }

        // Remove our hook from all events
        for (event, _) in hookEvents {
            guard var entries = hooks[event] as? [[String: Any]] else { continue }
            entries = entries.compactMap { entry in
                guard var entryHooks = entry["hooks"] as? [[String: Any]] else { return entry }
                entryHooks.removeAll { ($0["command"] as? String) == hookCommand }
                if entryHooks.isEmpty { return nil }
                var modified = entry
                modified["hooks"] = entryHooks
                return modified
            }
            if entries.isEmpty {
                hooks.removeValue(forKey: event)
            } else {
                hooks[event] = entries
            }
        }

        settings["hooks"] = hooks

        do {
            let data = try JSONSerialization.data(withJSONObject: settings, options: [.prettyPrinted, .sortedKeys])
            try data.write(to: settingsPath, options: .atomic)
        } catch {
            logger.error("Failed to update settings.json: \(error.localizedDescription)")
        }
    }
}
