import Foundation

/// Parsed Aseprite JSON export metadata.
///
/// Generated by: `aseprite -b --format json-array --data <name>.json --sheet <name>.png`
/// Used by SpriteSheetView when available; falls back to grid calculation otherwise.
struct SpriteMetadata: Codable {
    let frames: [Frame]
    let meta: Meta

    struct Frame: Codable {
        let filename: String
        let frame: Rect
        let rotated: Bool
        let trimmed: Bool
        let spriteSourceSize: Rect
        let sourceSize: Size
        let duration: Int  // milliseconds
    }

    struct Rect: Codable {
        let x: Int
        let y: Int
        let w: Int
        let h: Int
    }

    struct Size: Codable {
        let w: Int
        let h: Int
    }

    struct Meta: Codable {
        let app: String?
        let version: String?
        let image: String?
        let format: String?
        let size: Size?
        let scale: String?
        let frameTags: [FrameTag]?
    }

    struct FrameTag: Codable {
        let name: String
        let from: Int
        let to: Int
        let direction: String?
    }

    // MARK: - Helpers

    /// Total number of frames
    var frameCount: Int { frames.count }

    /// Average FPS derived from frame durations
    var fps: Double {
        guard !frames.isEmpty else { return 10 }
        let avgDuration = frames.map(\.duration).reduce(0, +) / frames.count
        return avgDuration > 0 ? 1000.0 / Double(avgDuration) : 10
    }

    /// Get frame rect at index
    func frameRect(at index: Int) -> (x: Int, y: Int, w: Int, h: Int)? {
        guard index >= 0, index < frames.count else { return nil }
        let f = frames[index].frame
        return (f.x, f.y, f.w, f.h)
    }

    /// Duration for frame at index (in seconds)
    func frameDuration(at index: Int) -> Double {
        guard index >= 0, index < frames.count else { return 0.1 }
        return Double(frames[index].duration) / 1000.0
    }

    // MARK: - Loading

    /// Load metadata from a JSON file in the bundle
    static func load(named name: String) -> SpriteMetadata? {
        guard let url = Bundle.main.url(forResource: name, withExtension: "json") else { return nil }
        guard let data = try? Data(contentsOf: url) else { return nil }
        return try? JSONDecoder().decode(SpriteMetadata.self, from: data)
    }

    /// Load metadata from an arbitrary file path
    static func load(from path: String) -> SpriteMetadata? {
        let url = URL(fileURLWithPath: path)
        guard let data = try? Data(contentsOf: url) else { return nil }
        return try? JSONDecoder().decode(SpriteMetadata.self, from: data)
    }
}
